### PR TITLE
updated signup page

### PR DESCRIPTION
**Pull request by phaneendrababu**
I updated the sign up page by using a form containing all the fields which was mentioned by you.

### CODE REVIEW

**Comment by adhavalboy** [comment]
css script should be in css/style.css

**Comment by phaneendrababu** [comment]
There is some problem if i add the css in the style.css . The problem is the existing css , css of sign up page have some common attributes (body attribute is common).

**Comment by adhavalboy** [comment]
remove common attribute and PR again

**Comment by adhavalboy** [comment]
Thank you @phaneendrababu

**Pull request merged**
